#!/bin/bash
#
# WPT Test Execution Script for FrankenBrowser
#
# This script automates the complete WPT test workflow:
# 1. Clones WPT repository if needed
# 2. Builds FrankenBrowser
# 3. Starts WebDriver server
# 4. Runs WPT test subset
# 5. Generates reports
# 6. Checks pass rate threshold

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
WPT_DIR="${WPT_DIR:-../wpt}"
BROWSER_BINARY="${BROWSER_BINARY:-target/release/frankenbrowser}"
WEBDRIVER_PORT="${WEBDRIVER_PORT:-4444}"
MIN_PASS_RATE="${MIN_PASS_RATE:-0.40}"
TEST_SUBSET="${TEST_SUBSET:-phase1}"
OUTPUT_DIR="${OUTPUT_DIR:-wpt-results}"
DATABASE="${DATABASE:-wpt-results/test-results.db}"

# Function to print colored messages
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Function to cleanup on exit
cleanup() {
    log_info "Cleaning up..."

    # Kill WebDriver server if running
    if [ -n "$WEBDRIVER_PID" ]; then
        log_info "Stopping WebDriver server (PID: $WEBDRIVER_PID)"
        kill $WEBDRIVER_PID 2>/dev/null || true
    fi

    # Kill browser process if running
    pkill -f frankenbrowser 2>/dev/null || true
}

trap cleanup EXIT

# Step 1: Clone WPT repository if needed
clone_wpt() {
    log_info "Checking WPT repository..."

    if [ -d "$WPT_DIR" ]; then
        log_success "WPT repository found at $WPT_DIR"

        # Update if it's a git repo
        if [ -d "$WPT_DIR/.git" ]; then
            log_info "Updating WPT repository..."
            (cd "$WPT_DIR" && git pull origin master) || log_warning "Failed to update WPT"
        fi
    else
        log_info "Cloning WPT repository to $WPT_DIR..."
        git clone --depth=1 https://github.com/web-platform-tests/wpt.git "$WPT_DIR"
        log_success "WPT repository cloned successfully"
    fi
}

# Step 2: Build FrankenBrowser
build_browser() {
    log_info "Building FrankenBrowser..."

    # Check if we're in the right directory
    if [ ! -f "Cargo.toml" ]; then
        log_error "Cargo.toml not found. Please run this script from the project root."
        exit 1
    fi

    # Build in release mode
    cargo build --release

    if [ ! -f "$BROWSER_BINARY" ]; then
        log_error "Browser binary not found at $BROWSER_BINARY after build"
        exit 1
    fi

    log_success "FrankenBrowser built successfully"
}

# Step 3: Start WebDriver server (as part of browser)
start_webdriver() {
    log_info "Starting WebDriver server on port $WEBDRIVER_PORT..."

    # Note: The actual WebDriver is embedded in the browser
    # We just need to ensure the browser is ready to accept connections

    # For now, we'll start the browser in the background with WebDriver enabled
    # This is a placeholder - actual implementation depends on browser's WebDriver mode

    # $BROWSER_BINARY --webdriver --webdriver-port=$WEBDRIVER_PORT &
    # WEBDRIVER_PID=$!

    # Wait for WebDriver to be ready
    # sleep 2

    # Test WebDriver connection
    # if ! curl -s "http://localhost:$WEBDRIVER_PORT/status" > /dev/null; then
    #     log_error "WebDriver server failed to start"
    #     exit 1
    # fi

    log_success "WebDriver server is ready (integrated with browser)"
}

# Step 4: Run WPT tests
run_tests() {
    log_info "Running WPT test subset: $TEST_SUBSET..."

    # Create output directory
    mkdir -p "$OUTPUT_DIR"

    # Determine which tests to run
    local test_list="tests/${TEST_SUBSET}-tests.txt"

    if [ ! -f "$test_list" ]; then
        log_warning "Test list not found: $test_list"
        log_info "Using default Phase 1 tests"
        test_list="tests/phase1-tests.txt"
    fi

    # Run tests using Rust test harness
    log_info "Executing tests from $test_list..."

    # Build and run the test harness
    cargo test --test wpt_runner -- --nocapture

    log_success "Test execution complete"
}

# Step 5: Generate reports
generate_reports() {
    log_info "Generating test reports..."

    # Reports are generated by the Rust test harness
    # Check if reports exist

    if [ -f "$OUTPUT_DIR/results.json" ]; then
        log_success "JSON report: $OUTPUT_DIR/results.json"
    fi

    if [ -f "$OUTPUT_DIR/results.html" ]; then
        log_success "HTML report: $OUTPUT_DIR/results.html"
        log_info "View report: file://$(pwd)/$OUTPUT_DIR/results.html"
    fi

    if [ -f "$OUTPUT_DIR/results.txt" ]; then
        log_success "Console report: $OUTPUT_DIR/results.txt"
        echo ""
        cat "$OUTPUT_DIR/results.txt"
        echo ""
    fi
}

# Step 6: Check pass rate threshold
check_pass_rate() {
    log_info "Checking pass rate threshold (minimum: ${MIN_PASS_RATE})..."

    # Extract pass rate from JSON report
    if [ -f "$OUTPUT_DIR/results.json" ]; then
        if command_exists jq; then
            local pass_rate=$(jq -r '.pass_rate' "$OUTPUT_DIR/results.json")
            local pass_rate_pct=$(echo "$pass_rate * 100" | bc -l)
            local min_pass_rate_pct=$(echo "$MIN_PASS_RATE * 100" | bc -l)

            log_info "Pass rate: ${pass_rate_pct}%"

            # Compare pass rates
            if (( $(echo "$pass_rate >= $MIN_PASS_RATE" | bc -l) )); then
                log_success "Pass rate meets threshold! ✅"
                return 0
            else
                log_error "Pass rate below threshold! ❌"
                log_error "Expected: ${min_pass_rate_pct}%, Actual: ${pass_rate_pct}%"
                return 1
            fi
        else
            log_warning "jq not installed, skipping pass rate check"
            log_info "Install jq: sudo apt-get install jq"
        fi
    else
        log_warning "Results JSON not found, skipping pass rate check"
    fi
}

# Main execution
main() {
    log_info "FrankenBrowser WPT Test Runner"
    log_info "=============================="
    echo ""

    # Parse command line arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            --skip-clone)
                SKIP_CLONE=1
                shift
                ;;
            --skip-build)
                SKIP_BUILD=1
                shift
                ;;
            --subset)
                TEST_SUBSET="$2"
                shift 2
                ;;
            --min-pass-rate)
                MIN_PASS_RATE="$2"
                shift 2
                ;;
            --help)
                echo "Usage: $0 [OPTIONS]"
                echo ""
                echo "Options:"
                echo "  --skip-clone        Skip cloning/updating WPT repository"
                echo "  --skip-build        Skip building FrankenBrowser"
                echo "  --subset NAME       Test subset to run (default: phase1)"
                echo "  --min-pass-rate N   Minimum pass rate (default: 0.40)"
                echo "  --help              Show this help message"
                echo ""
                echo "Environment variables:"
                echo "  WPT_DIR             WPT repository location (default: ../wpt)"
                echo "  BROWSER_BINARY      Browser binary path (default: target/release/frankenbrowser)"
                echo "  WEBDRIVER_PORT      WebDriver port (default: 4444)"
                echo "  OUTPUT_DIR          Output directory (default: wpt-results)"
                echo ""
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                echo "Run with --help for usage information"
                exit 1
                ;;
        esac
    done

    # Execute steps
    if [ -z "$SKIP_CLONE" ]; then
        clone_wpt
    fi

    if [ -z "$SKIP_BUILD" ]; then
        build_browser
    fi

    # start_webdriver  # Uncomment when WebDriver is ready

    run_tests

    generate_reports

    if ! check_pass_rate; then
        log_error "Test run failed: pass rate below threshold"
        exit 1
    fi

    log_success "All tests completed successfully! 🎉"
}

# Run main function
main "$@"
