openapi: 3.0.0
info:
  title: {{COMPONENT_NAME}} API
  version: {{API_VERSION}}
  description: |
    API contract for the {{COMPONENT_NAME}} component.

    {{COMPONENT_DESCRIPTION}}

  contact:
    name: API Support
    email: {{CONTACT_EMAIL}}
  license:
    name: {{LICENSE}}
    url: {{LICENSE_URL}}

servers:
  - url: http://localhost:{{PORT}}
    description: Development server
  - url: https://staging.{{DOMAIN}}/api/v1
    description: Staging server
  - url: https://{{DOMAIN}}/api/v1
    description: Production server

tags:
  - name: health
    description: Health check endpoints
  - name: {{RESOURCE_NAME}}
    description: {{RESOURCE_DESCRIPTION}}

paths:
  /health:
    get:
      summary: Health check
      description: Returns the health status of the service
      operationId: getHealth
      tags:
        - health
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
        '503':
          description: Service is unhealthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /health/ready:
    get:
      summary: Readiness check
      description: Returns whether the service is ready to accept requests
      operationId: getReadiness
      tags:
        - health
      responses:
        '200':
          description: Service is ready
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
        '503':
          description: Service is not ready
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /{{RESOURCE_PATH}}:
    get:
      summary: List {{RESOURCE_NAME}}
      description: Retrieve a list of {{RESOURCE_NAME}} with pagination
      operationId: list{{RESOURCE_CLASS}}
      tags:
        - {{RESOURCE_NAME}}
      parameters:
        - name: page
          in: query
          description: Page number (1-indexed)
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: page_size
          in: query
          description: Number of items per page
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: sort
          in: query
          description: Sort field and direction (e.g., "created_at:desc")
          required: false
          schema:
            type: string
            pattern: '^[a-z_]+:(asc|desc)$'
        - name: filter
          in: query
          description: Filter criteria (JSON object)
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/{{RESOURCE_CLASS}}List'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - bearerAuth: []

    post:
      summary: Create {{RESOURCE_NAME}}
      description: Create a new {{RESOURCE_NAME}} resource
      operationId: create{{RESOURCE_CLASS}}
      tags:
        - {{RESOURCE_NAME}}
      requestBody:
        description: {{RESOURCE_CLASS}} object to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/{{RESOURCE_CLASS}}Create'
      responses:
        '201':
          description: Successfully created
          headers:
            Location:
              description: URI of the created resource
              schema:
                type: string
                format: uri
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/{{RESOURCE_CLASS}}'
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Resource already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - bearerAuth: []

  /{{RESOURCE_PATH}/{id}:
    get:
      summary: Get {{RESOURCE_NAME}} by ID
      description: Retrieve a specific {{RESOURCE_NAME}} by its ID
      operationId: get{{RESOURCE_CLASS}}ById
      tags:
        - {{RESOURCE_NAME}}
      parameters:
        - name: id
          in: path
          description: {{RESOURCE_CLASS}} ID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/{{RESOURCE_CLASS}}'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - bearerAuth: []

    put:
      summary: Update {{RESOURCE_NAME}}
      description: Update an existing {{RESOURCE_NAME}} (full replacement)
      operationId: update{{RESOURCE_CLASS}}
      tags:
        - {{RESOURCE_NAME}}
      parameters:
        - name: id
          in: path
          description: {{RESOURCE_CLASS}} ID
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: Updated {{RESOURCE_CLASS}} object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/{{RESOURCE_CLASS}}Update'
      responses:
        '200':
          description: Successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/{{RESOURCE_CLASS}}'
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - bearerAuth: []

    patch:
      summary: Partially update {{RESOURCE_NAME}}
      description: Partially update an existing {{RESOURCE_NAME}}
      operationId: patch{{RESOURCE_CLASS}}
      tags:
        - {{RESOURCE_NAME}}
      parameters:
        - name: id
          in: path
          description: {{RESOURCE_CLASS}} ID
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: Fields to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/{{RESOURCE_CLASS}}Patch'
      responses:
        '200':
          description: Successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/{{RESOURCE_CLASS}}'
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - bearerAuth: []

    delete:
      summary: Delete {{RESOURCE_NAME}}
      description: Delete a {{RESOURCE_NAME}} by ID
      operationId: delete{{RESOURCE_CLASS}}
      tags:
        - {{RESOURCE_NAME}}
      parameters:
        - name: id
          in: path
          description: {{RESOURCE_CLASS}} ID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Successfully deleted (no content)
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT authentication token

  schemas:
    HealthResponse:
      type: object
      required:
        - status
        - timestamp
      properties:
        status:
          type: string
          enum: [healthy, unhealthy]
          example: healthy
        timestamp:
          type: string
          format: date-time
          example: "2025-01-04T10:30:00Z"
        version:
          type: string
          example: "1.0.0"
        checks:
          type: object
          additionalProperties:
            type: object
            properties:
              status:
                type: string
                enum: [up, down]
              message:
                type: string

    {{RESOURCE_CLASS}}:
      type: object
      required:
        - id
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
          example: "123e4567-e89b-12d3-a456-426614174000"
        created_at:
          type: string
          format: date-time
          readOnly: true
          example: "2025-01-04T10:30:00Z"
        updated_at:
          type: string
          format: date-time
          readOnly: true
          example: "2025-01-04T10:30:00Z"
        # Add resource-specific fields here
        {{RESOURCE_FIELDS}}

    {{RESOURCE_CLASS}}Create:
      type: object
      required: []
        # Add required fields for creation
      properties:
        # Add fields needed for resource creation
        {{RESOURCE_CREATE_FIELDS}}

    {{RESOURCE_CLASS}}Update:
      type: object
      properties:
        # Add fields that can be updated
        {{RESOURCE_UPDATE_FIELDS}}

    {{RESOURCE_CLASS}}Patch:
      type: object
      properties:
        # Add fields that can be partially updated
        {{RESOURCE_PATCH_FIELDS}}

    {{RESOURCE_CLASS}}List:
      type: object
      required:
        - data
        - pagination
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/{{RESOURCE_CLASS}}'
        pagination:
          $ref: '#/components/schemas/Pagination'

    Pagination:
      type: object
      required:
        - page
        - page_size
        - total_items
        - total_pages
      properties:
        page:
          type: integer
          minimum: 1
          example: 1
        page_size:
          type: integer
          minimum: 1
          maximum: 100
          example: 20
        total_items:
          type: integer
          minimum: 0
          example: 150
        total_pages:
          type: integer
          minimum: 0
          example: 8
        has_next:
          type: boolean
          example: true
        has_previous:
          type: boolean
          example: false

    Error:
      type: object
      required:
        - message
        - code
      properties:
        message:
          type: string
          description: Human-readable error message
          example: "Invalid request parameters"
        code:
          type: string
          description: Machine-readable error code
          example: "VALIDATION_ERROR"
        details:
          type: object
          description: Additional error details
          additionalProperties: true
        timestamp:
          type: string
          format: date-time
          example: "2025-01-04T10:30:00Z"
        request_id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"

# Variable Reference:
# {{COMPONENT_NAME}} - Name of the component (e.g., "User API")
# {{API_VERSION}} - API version (e.g., "1.0.0")
# {{COMPONENT_DESCRIPTION}} - Brief description of the API
# {{CONTACT_EMAIL}} - Support email address
# {{LICENSE}} - License name (e.g., "MIT")
# {{LICENSE_URL}} - License URL
# {{PORT}} - Development port (e.g., "8000")
# {{DOMAIN}} - Production domain (e.g., "example.com")
# {{RESOURCE_NAME}} - Resource name (e.g., "users")
# {{RESOURCE_DESCRIPTION}} - Resource description
# {{RESOURCE_CLASS}} - Resource class name (e.g., "User")
# {{RESOURCE_PATH}} - Resource path (e.g., "users")
# {{RESOURCE_FIELDS}} - Resource-specific fields
# {{RESOURCE_CREATE_FIELDS}} - Fields for creation
# {{RESOURCE_UPDATE_FIELDS}} - Fields for update
# {{RESOURCE_PATCH_FIELDS}} - Fields for partial update
